version: "3.9"

services:
  ytbot:
    container_name: yt2tg
    build: .
    restart: always
    mem_limit: 512m
    memswap_limit: 1g
    volumes:
      - ./config.json:/app/config.json:ro
    environment:
      - TZ=Europe/Berlin
